spring:
  h2:
    console:
      enabled: true
      path: /h2console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: